### ISSUE TITLE
Add Codestyle configuration for Eclipse

### ISSUE THREAD

**Issue by leostrakosch** [SupunArunoda/CPACEP#16]
Every developer on CPACEP should use the same code style.
We thus should add a code style configuration for eclipse.
Ideally, we should also provide some formatting-mechanism.

One possbility would be https://github.com/google/google-java-format

**Comment by SupunArunoda** [comment]
Hi Thomas,
Currently I'm using google code formatter.

**Comment by leostrakosch** [comment]
So we should have a maven goal that runs the google code formatter with your options
and provide an eclipse configuration that is as close to google code formatter as possible
(e.g., spaces instead of tabs, correct number of spaces for indentation would be very important).

**Comment by leostrakosch** [comment]
Introduced in #17 .
