### ISSUE TITLE
Dropdowns for Specification and Configuration could have meaningful Defaults

### ISSUE THREAD

**Issue by leostrakosch** [SupunArunoda/CPACEP#22]
Since the dropdowns for specification and configuration have a label that tells
users what they are for,
the current placeholders 'Specification' and 'Configuration'
could be replaced with existing, meaningful default values.

Both for the Specification and Configuration, a `default` exists.
This could be used as the default value for both, so that user's can use that if they don't have any preference.

**Comment by SupunArunoda** [comment]
Hi Thomas,
Which means we have to set **default** to both specification and configuration combos when creating new configuration?

**Comment by leostrakosch** [comment]
Yupp, and maybe leave the 'Specification' and 'Configuration' if that doesn't exist?
