### ISSUE TITLE
Sort Specification and Configuration dropdown entries lexicographically

### ISSUE THREAD

**Issue by leostrakosch** [SupunArunoda/CPACEP#4]
Currently, the entries in the dropdowns for specification and configuration of CPAchecker are not sorted.

E.g., in the specification dropdown, the order is: "MainEntry, TerminatingFunctions, deadlock",
and in the configuration dropdown, the order is: "witness-validation, witnessValidation, apronAnalysis-Cegar" .

For easier search, these should be sorted lexicographically.

In addition, since configurations often have one short version with a 'best by experience' configuration and multiple alternatives (e.g., `valueAnalysis` and `valueAnalysis-featureVars`),
it would be nice to have the short version shown first (but this should actually be the default for lexicographic sort).

**Comment by SupunArunoda** [comment]
Hi @leostrakosch ,
Added this feature. But some of the specification and configurations have started with capital letters. Therefore when we sort, those words came first. Is it fine?

**Comment by leostrakosch** [comment]
Hi Supun,

do all capital letters come prior to all lowercase letters (i.e., A-Z and
then a-z) or is it capital before the corresponding Aa-Zz?
The latter is OK, but the first wouldn't be the best solution - there is no
reason to group all configs that start with uppercase together.

Supun Arunoda <notifications@github.com> schrieb am Mo., 4. Juni 2018,
18:50:

**Comment by leostrakosch** [comment]
I don't believe that this is solved as required.
Doesn't it now show all configurations in lower case, even if they actually start with an uppercase letter?
In addition, how about camel case? The method `toLowerCase` transforms **all** letters in a String to lower case.

There actually is a mechanism in Java to sort case insensitive:
`Collections.sort(matchedList, String.CASE_INSENSITIVE_ORDER);`

**Comment by SupunArunoda** [comment]
How about adding first letter as capital ?

**Comment by leostrakosch** [comment]
I'm not sure I get what you mean. But why don't you just use sort with `String.CASE_INSENSITIVE_ORDER`, as said above?
This will immediately solve the issue.

**Comment by SupunArunoda** [comment]
Hi Thomas,
This doesn't work for me.. That's why I followed another approach..

**Comment by leostrakosch** [comment]
Let's discuss it in the PR #10 :-)
