### ISSUE TITLE
CPAchecker doesn't print to Eclipse console

### ISSUE THREAD

**Issue by leostrakosch** [SupunArunoda/CPACEP#6]
When running CPAchecker from within CPACEP, no output is shown on the console.
From the Eclipse instance from which I started CPACEP, I can see that files are copied, but nothing is shown in CPACEP.

Do I have to open some specific view instead of Console, or is this not supported yet?

**Comment by SupunArunoda** [comment]
Hi @leostrakosch ,
Result output will print in parent eclipse, not the eclipse instance.  Attached the screen-shot. Result user interface will be implemented in week 6. : )
![screenshot from 2018-05-29 13-22-53](https://user-images.githubusercontent.com/12041588/40645267-796538da-6343-11e8-84c2-6d461c81a48f.png)

**Comment by leostrakosch** [comment]
Hi Supun,

the Eclipse instance running CPACEP only shows the files copied, see the attached screenshot.
The screenshot also contains my configuration for running CPAchecker.

Maybe your state of CPACEP is not completely pushed yet? Or am I missing some configuration option?

![screenshot from 2018-05-29 10-05-56](https://user-images.githubusercontent.com/4499519/40645948-26baa630-6328-11e8-8ac1-f2d164dd8dd2.png)

**Comment by SupunArunoda** [comment]
Hi @leostrakosch ,
Didn't you click on Run button?

**Comment by SupunArunoda** [comment]
Please delete the existing configurations(Run CPAchecker and New_configuration) before running. Make sure to get updates now. I have fixed #1 and #2 bugs.

**Comment by leostrakosch** [comment]
Hi Supun,

The output
```
Running CPAchecker with default heap size (1200M). Specify a larger value with -heap if you have more RAM.
Running CPAchecker with default stack size (1024k). Specify a larger value with -stack if needed.
```
is shown in the original Eclipse window now, but warnings and the verdict is not.

But since it is at least somehow working now - would it be possible to show this output in the Console window of the running Eclipse session?
Users usually only want to have one eclipse instance running.

**Comment by SupunArunoda** [comment]
Hi @leostrakosch ,
#1 , #2  and #6 issues are fixed from [this commit](https://github.com/SupunArunoda/CPACEP/commit/6e5bc1f47fc152853b0528b8efbde7b77ddc558c). Please get update and remove existing configurations before executing.

**Comment by leostrakosch** [comment]
Hi Supun,

again: would it be possible to show this output in the Console window of the running Eclipse session?
Users usually only want to have one eclipse instance running.

In addition, please try to commit separate changes separately, so that it is easier to understand which code changes belong together. See https://sethrobertson.github.io/GitBestPractices/ for best practices on git.

For understanding, could you tell me which changes in 6e5bc1f47 fix this issue?

**Comment by leostrakosch** [comment]
We don't need the whole output window, but a text output to the console is necessary for users to use the plugin.
A quick search gave me the following result for writing to the Eclipse console directly, I'm not sure whether it's outdated, but it seems that it is possible to write to the Console view:
https://wiki.eclipse.org/FAQ_How_do_I_write_to_the_console_from_a_plug-in%3F

**Comment by leostrakosch** [comment]
From the above URL:

Many of the people asking this question are confused by the fact that two Eclipse instances are in use when you are developing plug-ins. One is the development platform you are using as your IDE, and the other is the target platform&#151;also known as the runtime workbench&#151;consisting of the plug-ins in the development workbench you are testing against. When a plug-in in the target platform writes a message to System.out or System.err, the message appears in the Console view of the development platform. This view emulates the Java console that appears when Eclipse runs under Windows with java.exe. You should be writing to the console only in this manner when in debug mode (see FAQ_How_do_I_use_the_platform_debug_tracing_facility?).


In some situations however, a plug-in in the development platform has a legitimate reason to write to the development platform Console view. Some tools originally designed for the command line, such as Ant and CVS, traditionally use console output as a way of communicating results to the tool user. When these tools are ported for use with an IDE, this console output is typically replaced with richer forms of feedback, such as views, markers, and decorations. However, users accustomed to the old command-line output may still want to see this raw output as an alternative to other visual forms of feedback. Tools in this category can use the Console view to write this output.


Prior to Eclipse 3.0, each plug-in that wanted console-like output created its own Console view. Eclipse 3.0 provides a single generic Console view that all plug-ins can write to. The view can host several console documents at once and allows the user to switch between different console pages. Each page in the console is represented by an org.eclipse.ui.console.IConsole object. To write to the console, you need to create your own IConsole instance and connect it to the Console view. To do this, you have to add a new dependency to org.eclipse.ui.console in the plugin.xml of your plugin. For a console containing a simple text document, you can instantiate a MessageConsole instance. Here is a method that locates a console with a given name and creates a new one if it cannot be found:

```
   private MessageConsole findConsole(String name) {
      ConsolePlugin plugin = ConsolePlugin.getDefault();
      IConsoleManager conMan = plugin.getConsoleManager();
      IConsole[] existing = conMan.getConsoles();
      for (int i = 0; i < existing.length; i++)
         if (name.equals(existing[i].getName()))
            return (MessageConsole) existing[i];
      //no console found, so create a new one
      MessageConsole myConsole = new MessageConsole(name, null);
      conMan.addConsoles(new IConsole[]{myConsole});
      return myConsole;
   }
```
Once a console is created, you can write to it either by directly modifying its IDocument or by opening an output stream on the console. This snippet opens a stream and writes some text to a console:
```
   MessageConsole myConsole = findConsole(CONSOLE_NAME);
   MessageConsoleStream out = myConsole.newMessageStream();
   out.println("Hello from Generic console sample action");
```
Creating a console and writing to it do not create or reveal the Console view. If you want to make that sure the Console view is visible, you need to reveal it using the usual workbench API. Even once the Console view is revealed, keep in mind that it may contain several pages, each representing a different IConsole provided by a plug-in. Additional API asks the Console view to display your console. This snippet reveals the Console view and asks it to display a particular console instance:
```
  IConsole myConsole = ...;// your console instance
  IWorkbenchPage page = ...;// obtain the active page
  String id = IConsoleConstants.ID_CONSOLE_VIEW;
  IConsoleView view = (IConsoleView) page.showView(id);
  view.display(myConsole);
```
