### ISSUE TITLE
CPACEP should be Operating-System agnostic

### ISSUE THREAD

**Issue by leostrakosch** [SupunArunoda/CPACEP#9]
Currently, CPACEP only works in Linux/Unix(?) systems
because the file delimiter `/` is hard-coded
and it is assumed that the temporary directory is created in `/tmp/`.

This makes it unusable at least in Windows.

Instead, we should use `File.separator` as path delimiters
and remember the created temporary directory.

**Comment by leostrakosch** [comment]
It should also be possible to specify the `cpa.bat` as CPAchecker executable.
Currently, `cpa.sh` is hardcoded in `CPACEPConnector`.

**Comment by leostrakosch** [comment]
Are you already working on this? Do you have a Windows machine available?
Otherwise I'll fix it on Monday.

**Comment by SupunArunoda** [comment]
Hi Thomas,
yes. Can you remember there was an issue when running CPAChecker on windows. You told me that there was no documentation at the moment? Check email conversation.
![mathsat_error](https://user-images.githubusercontent.com/12041588/41192385-7e76dd1c-6c1a-11e8-8442-2f5c1099ffc6.PNG)

**Comment by leostrakosch** [comment]
Hi Supun,

yes, this failure is fine and can be circumvented by specifying a different
solver (-setprop solver.solver=SMTInterpol and some others), but it should
still be possible to start cpachecker within cpacep and see this message.
There is just no documentation for building mathsat5 as needed (as far as I
know).

So does "yes" mean that you will work on it? ;-)

Supun Arunoda <notifications@github.com> schrieb am Sa., 9. Juni 2018,
15:53:

**Comment by leostrakosch** [comment]
Reopen due to premature merge of PR.

**Comment by leostrakosch** [comment]
Working since 5191fe2
